Document: osdlyrics
Title: Debian osdlyrics Manual
Author: <insert document author here>
Abstract: This manual describes what osdlyrics is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/osdlyrics/osdlyrics.sgml.gz

Format: postscript
Files: /usr/share/doc/osdlyrics/osdlyrics.ps.gz

Format: text
Files: /usr/share/doc/osdlyrics/osdlyrics.text.gz

Format: HTML
Index: /usr/share/doc/osdlyrics/html/index.html
Files: /usr/share/doc/osdlyrics/html/*.html
